export type Project = {
  id: number
  title: string
  category: string
  year: string
  tags: string[]
  desc: string
  gradient: string
  accent: string
  span: 'wide' | 'normal'
  image?: string
  images?: string[]
  imageLayout?: 'default' | 'first-full-then-2col' | '2col-then-full' | 'full-then-wide-pair'
  gridPairStart?: number
  coverZoom?: number
  wideSpacing?: boolean
  postCoverImage?: string
  video?: string
  siteUrl?: string
  pageBg?: string
}

export const PROJECTS: Project[] = [
  {
    id: 0,
    title: 'NETS Energy',
    category: 'Web Design',
    year: '2025',
    tags: ['Energy', 'Web Design', 'HVAC'],
    desc: 'Full website design and development for NETS Energy — a leading HVAC solution provider with an animated, conversion-focused digital presence.',
    gradient: 'linear-gradient(135deg, #0a1e2e 0%, #0d3050 100%)',
    accent: '#38bdf8',
    span: 'wide',
    image: '/nets-cover.png',
    images: ['/nets-screenshot.png', '/nets-sm.jpg'],
  },
  {
    id: 25,
    title: 'Pacific Consulting',
    category: 'Web Design',
    year: '2025',
    tags: ['ERP', 'Web Design', 'Consulting'],
    desc: 'Website design and development for Pacific Consulting — a Microsoft Dynamics 365 solutions partner driving digital transformation for enterprise clients.',
    gradient: 'linear-gradient(135deg, #0a0e1c 0%, #141830 60%, #080c1a 100%)',
    accent: '#fb923c',
    span: 'normal',
    image: '/pacific-cover.png',
    coverZoom: 1.4,
    images: [
      '/pacific-website.png',
      '/pacific-2.png',
      '/pacific-3.png',
    ],
  },
  {
    id: 21,
    title: 'Avyanna Aviation',
    category: 'Web Design',
    year: '2025',
    tags: ['Aviation', 'Web Design', 'Education'],
    desc: 'Full website design and development for Avyanna Aviation Academy — a premier pilot training institute with a bold, conversion-driven digital presence.',
    gradient: 'linear-gradient(135deg, #0a1628 0%, #0d2a50 100%)',
    accent: '#6096ff',
    span: 'wide',
    image: '/avyanna-cover.jpg',
    video: '/avyanna.mp4',
    images: ['/avyanna-ss.png', '/avyanna-ss2.jpg', '/avyanna-ss3.png', '/avyanna-ss4.png'],
    imageLayout: 'first-full-then-2col',
    pageBg: 'linear-gradient(170deg, #e2e2e2 0%, #b8b8b8 100%)',
  },
  {
    id: 24,
    title: 'VFTI',
    category: 'Web Design',
    year: '2025',
    tags: ['Aviation', 'Web Design', 'Pilot Training'],
    desc: 'Website design and development for Vision Flying Training Institute — a DGCA-approved pilot training organisation based in Amreli, Gujarat.',
    gradient: 'linear-gradient(135deg, #060c1a 0%, #0c1a38 60%, #081228 100%)',
    accent: '#60a5fa',
    span: 'normal',
    image: '/vfti-cover.jpg',
    wideSpacing: true,
    postCoverImage: '/vfti-mockup2.jpg',
    video: '/vfti.mp4',
    images: ['/vfti-artboard.png', '/vfti-artboard2.png', '/vfti-mockup3.jpg'],
    pageBg: 'linear-gradient(170deg, #e2e2e2 0%, #b8b8b8 100%)',
  },
  {
    id: 23,
    title: 'FSTC',
    category: 'Web Design',
    year: '2025',
    tags: ['Aviation', 'Web Design', 'Education'],
    desc: 'Full website design and development for Flight Simulation Technique Centre — India\'s premier DGCA & EASA approved pilot training organisation.',
    gradient: 'linear-gradient(135deg, #080e1e 0%, #0d1a3a 60%, #061228 100%)',
    accent: '#3b82f6',
    span: 'wide',
    image: '/fstc-cover.jpg',
    wideSpacing: true,
    images: ['/fstc-2.jpg', '/fstc-3.png', '/fstc-4.mp4', '/fstc-6.png', '/fstc-5.png', '/fstc-7.png', '/fstc-8.png'],
    imageLayout: 'full-then-wide-pair',
    gridPairStart: 3,
  },
  {
    id: 22,
    title: 'The Qila',
    category: 'Brand Design',
    year: '2025',
    tags: ['Branding', 'Hospitality', 'Identity'],
    desc: 'Complete brand identity for The Qila Hotel & Banquet — a heritage-inspired visual system rooted in warmth, elegance, and architectural legacy.',
    gradient: 'linear-gradient(135deg, #2a1a08 0%, #4a2e12 60%, #1e1006 100%)',
    accent: '#c8956c',
    span: 'wide',
    image: '/qila-01.jpg',
    images: [
      '/qila-01.jpg',
      '/qila-02.jpg',
      '/qila-03.jpg',
      '/qila-04.jpg',
      '/qila-05.jpg',
      '/qila-06.jpg',
      '/qila-08.jpg',
      '/qila-09.jpg',
    ],
  },
  {
    id: 26,
    title: 'Omar Bazaz',
    category: 'Web Design',
    year: '2025',
    tags: ['Photography', 'Portfolio', 'E-Commerce'],
    desc: 'Portfolio and fine art print store for photographer Omar Bazaz — a minimalist digital showcase built to sell archival-quality prints.',
    gradient: 'linear-gradient(135deg, #0c0a08 0%, #1e1810 60%, #0e0b08 100%)',
    accent: '#d4a97a',
    span: 'wide',
    image: '/omarbazaz-cover.jpg',
    video: '/omarbazaz-2.mp4',
    images: [
      '/omarbazaz-5.png',
      '/omarbazaz-3.png',
      '/omarbazaz-4.png',
    ],
  },
  {
    id: 27,
    title: 'The Sarai',
    category: 'Brand Design',
    year: '2025',
    tags: ['Branding', 'Hospitality', 'Identity'],
    desc: 'Complete brand identity for The Sarai — a warm, heritage-inspired visual system built around luxury hospitality, earthy tones, and timeless craftsmanship.',
    gradient: 'linear-gradient(135deg, #1a0a08 0%, #3a1a10 60%, #1a0c08 100%)',
    accent: '#c4956a',
    span: 'wide',
    image: '/sarai-cover.png',
    images: [
      '/sarai-1.png',
      '/sarai-2.png',
      '/sarai-3.png',
      '/sarai-4.png',
      '/sarai-5.png',
      '/sarai-6.png',
      '/sarai-7.png',
      '/sarai-8.png',
    ],
  },
  {
    id: 36,
    title: 'Flavour Hub',
    category: 'Brand Design',
    year: '2025',
    tags: ['Branding', 'Identity', 'F&B'],
    desc: 'Brand identity design for Flavour Hub — a bold, modern food distribution brand built around quality sourcing and striking visual presence across print and motion.',
    gradient: 'linear-gradient(135deg, #0a0f1e 0%, #111a30 100%)',
    accent: '#84cc16',
    span: 'wide',
    image: '/flavourhub-cover.png',
    video: '/flavourhub.mp4',
    images: [
      '/flavourhub-05.jpg',
      '/flavourhub-06.jpg',
      '/flavourhub-07.jpg',
      '/flavourhub-08.jpg',
      '/flavourhub-09.jpg',
      '/flavourhub-10.jpg',
    ],
  },
  {
    id: 35,
    title: 'WTE',
    category: 'Print Media',
    year: '2026',
    tags: ['Print', 'Stationery', 'Corporate'],
    desc: 'Print media and stationery design for WTE — a corporate identity collateral suite including branded diaries, letterheads, and print assets.',
    gradient: 'linear-gradient(135deg, #061628 0%, #0d2a4a 100%)',
    accent: '#3b82f6',
    span: 'wide',
    image: '/wte-cover.jpg',
    images: [
      '/wte-02.jpg',
      '/wte-01.jpg',
      '/wte-03.png',
      '/wte-04.png',
      '/wte-05.png',
      '/wte-06.png',
    ],
  },
  {
    id: 34,
    title: 'Nirvana Holidays',
    category: 'Brand Design',
    year: '2025',
    tags: ['Branding', 'Identity', 'Travel'],
    desc: 'Brand identity design for Nirvana Holidays — a sleek, modern travel brand with a refined visual language built around motion and exploration.',
    gradient: 'linear-gradient(135deg, #0d1117 0%, #1a2030 100%)',
    accent: '#a0aec0',
    span: 'wide',
    image: '/nirvana-cover.jpg',
    images: [
      '/nirvana-1.jpg',
      '/nirvana-2.jpg',
      '/nirvana-3.jpg',
      '/nirvana-4.jpg',
      '/nirvana-5.jpg',
    ],
  },
  {
    id: 33,
    title: 'Abyad',
    category: 'Brand Design',
    year: '2025',
    tags: ['Branding', 'Packaging', 'Identity'],
    desc: 'Brand identity and packaging design for Abyad — a premium nuts, dried fruits & dates brand with an elegant, nature-inspired visual system.',
    gradient: 'linear-gradient(135deg, #0b1f1e 0%, #123430 100%)',
    accent: '#5eada0',
    span: 'wide',
    image: '/abyad-1.png',
    images: [
      '/abyad-2.png',
      '/abyad-3.png',
      '/abyad-4.png',
      '/abyad-5.png',
      '/abyad-6.png',
      '/abyad-7.png',
      '/abyad-8.png',
      '/abyad-9.png',
    ],
  },
  {
    id: 32,
    title: 'The Local Shack',
    category: 'Brand Design',
    year: '2025',
    tags: ['Branding', 'Identity', 'F&B'],
    desc: 'Brand identity design for The Locale Shack — a rustic, tropical bites & brews concept with a bold hand-crafted visual language.',
    gradient: 'linear-gradient(135deg, #1a1005 0%, #2e1f08 100%)',
    accent: '#f59e0b',
    span: 'wide',
    image: '/localshack-1.png',
    images: [
      '/localshack-2.png',
      '/localshack-3.png',
      '/localshack-4.png',
      '/localshack-5.png',
      '/localshack-6.png',
      '/localshack-7.png',
      '/localshack-8.png',
      '/localshack-9.png',
    ],
  },
  {
    id: 31,
    title: 'Shikara',
    category: 'Brand Design',
    year: '2025',
    tags: ['Branding', 'Identity', 'Travel'],
    desc: 'Brand identity design for Shikara Travels — a clean, elegant visual system built around the iconic Kashmiri shikara, capturing the spirit of authentic travel.',
    gradient: 'linear-gradient(135deg, #0f1a24 0%, #1a2e3a 100%)',
    accent: '#7ab8d4',
    span: 'wide',
    image: '/shikara-1.png',
    images: [
      '/shikara-2.png',
      '/shikara-3.png',
      '/shikara-4.png',
      '/shikara-5.png',
      '/shikara-6.png',
      '/shikara-7.png',
    ],
  },
  {
    id: 30,
    title: 'Obba',
    category: 'Brand Design',
    year: '2025',
    tags: ['Branding', 'Identity', 'Logo'],
    desc: 'Complete brand identity design for Obba — a bold visual system built from the ground up, spanning logo, typography, colour, and brand collateral.',
    gradient: 'linear-gradient(135deg, #1a1208 0%, #2e1f0a 100%)',
    accent: '#c9a96e',
    span: 'wide',
    image: '/obba-1.png',
    images: [
      '/obba-2.png',
      '/obba-3.png',
      '/obba-4.png',
      '/obba-5.png',
      '/obba-6.png',
      '/obba-7.png',
      '/obba-10.png',
      '/obba-11.png',
      '/obba-9.png',
      '/obba-8.png',
    ],
  },
  {
    id: 37,
    title: 'Mountain Cottage',
    category: 'Brand Design',
    year: '2025',
    tags: ['Branding', 'Identity', 'Hospitality'],
    desc: 'Brand identity design for The Mountain Cottage — a refined, nature-inspired visual system built around warmth, wilderness, and rustic luxury.',
    gradient: 'linear-gradient(135deg, #0d1208 0%, #1a2010 100%)',
    accent: '#c8b97a',
    span: 'wide',
    image: '/mountaincottage-1.png',
    images: [
      '/mountaincottage-2.png',
      '/mountaincottage-3.png',
      '/mountaincottage-4.png',
      '/mountaincottage-5.png',
      '/mountaincottage.m3u8',
    ],
  },
]
